/**
 * All icons must be added to this module.
 * Exposed via '@/icons'
 */
import _ArgumentIcon from './argument.svg';
import _ChevronDownIcon from './chevron-down.svg';
import _ChevronLeftIcon from './chevron-left.svg';
import _ChevronUpIcon from './chevron-up.svg';
import _CloseIcon from './close.svg';
import _CopyIcon from './copy.svg';
import _DeprecatedArgumentIcon from './deprecated-argument.svg';
import _DeprecatedEnumValueIcon from './deprecated-enum-value.svg';
import _DeprecatedFieldIcon from './deprecated-field.svg';
import _DirectiveIcon from './directive.svg';
import _DocsFilledIcon from './docs-filled.svg';
import _DocsIcon from './docs.svg';
import _EnumValueIcon from './enum-value.svg';
import _FieldIcon from './field.svg';
import _HistoryIcon from './history.svg';
import _ImplementsIcon from './implements.svg';
import _KeyboardShortcutIcon from './keyboard-shortcut.svg';
import _MagicWand from './magic-wand.svg';
import _MagnifyingGlassIcon from './magnifying-glass.svg';
import _MergeIcon from './merge.svg';
import _PenIcon from './pen.svg';
import _PlayIcon from './play.svg';
import _PlusIcon from './plus.svg';
import _PrettifyIcon from './prettify.svg';
import _ProgrammingCode from './programming-code.svg';
import _ReloadIcon from './reload.svg';
import _RootTypeIcon from './root-type.svg';
import _Run from './run.svg';
import _SettingsIcon from './settings.svg';
import _StarFilledIcon from './star-filled.svg';
import _StarIcon from './star.svg';
import _StopIcon from './stop.svg';
import _Table from './table.svg';
import _TrashIcon from './trash.svg';
import _TypeIcon from './type.svg';
import { Icon } from './Icon';

export const ArgumentIcon = Icon(_ArgumentIcon);
export const ChevronDownIcon = Icon(_ChevronDownIcon);
export const ChevronLeftIcon = Icon(_ChevronLeftIcon);
export const ChevronUpIcon = Icon(_ChevronUpIcon);
export const CloseIcon = Icon(_CloseIcon);
export const CopyIcon = Icon(_CopyIcon);
export const DeprecatedArgumentIcon = Icon(_DeprecatedArgumentIcon);
export const DeprecatedEnumValueIcon = Icon(_DeprecatedEnumValueIcon);
export const DeprecatedFieldIcon = Icon(_DeprecatedFieldIcon);
export const DirectiveIcon = Icon(_DirectiveIcon);
export const DocsFilledIcon = Icon(_DocsFilledIcon, 'filled docs icon');
export const DocsIcon = Icon(_DocsIcon);
export const EnumValueIcon = Icon(_EnumValueIcon);
export const FieldIcon = Icon(_FieldIcon);
export const HistoryIcon = Icon(_HistoryIcon);
export const ImplementsIcon = Icon(_ImplementsIcon);
export const KeyboardShortcutIcon = Icon(_KeyboardShortcutIcon);
export const MagicWand = Icon(_MagicWand);
export const MagnifyingGlassIcon = Icon(_MagnifyingGlassIcon);
export const MergeIcon = Icon(_MergeIcon);
export const PenIcon = Icon(_PenIcon);
export const PlayIcon = Icon(_PlayIcon);
export const PlusIcon = Icon(_PlusIcon);
export const PrettifyIcon = Icon(_PrettifyIcon);
export const ProgrammingCode = Icon(_ProgrammingCode);
export const ReloadIcon = Icon(_ReloadIcon);
export const RootTypeIcon = Icon(_RootTypeIcon);
export const RunIcon = Icon(_Run);
export const SettingsIcon = Icon(_SettingsIcon);
export const StarFilledIcon = Icon(_StarFilledIcon, 'filled star icon');
export const StarIcon = Icon(_StarIcon);
export const StopIcon = Icon(_StopIcon);
export const TableIcon = Icon(_Table);
export const TrashIcon = Icon(_TrashIcon, 'trash icon');
export const TypeIcon = Icon(_TypeIcon);
